### ISSUE TITLE
synchronous call limits too strict

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-openshift-driver#129]
@sophieherrmann we've talked about this. I'm just logging it here so that it's documented.

In my opinion the limits for the synchronous call are too strict. 
On a quite small process graph I receive the error:
```
SERVER-ERROR: The supplied process graph is too big to be processed synchronously. Either run it as asynchronous job or try to use a shorter time span / smaller bounding box / less collections.
```

It's a nice error message. Definitely useful for the user. 
But the message (or the limits) are misleading. The tested process graph uses one collection, looks at one pixel, has 3 nodes and ca. 25 time steps.
So the reductions in time span, bounding box and collections are not really possible.

Maybe you can think about the logic of defining the limits (you mentioned currently its nodes*collections), the error threshold used to trigger the error and maybe adapt the error message to the variables that define the limit. 

Here the process graph I used:
```
{
  "id": "test",
  "process_graph": {
    "load_collection_WJSXI6057X": {
      "process_id": "load_collection",
      "arguments": {
        "id": "boa_sentinel_2",
        "spatial_extent": {
          "west": 11.5383,
          "east": 11.5383,
          "south": 46.4867,
          "north": 46.4867
        },
        "temporal_extent": [
          "2016-01-07T12:00:00Z",
          "2016-04-29T12:00:00Z"
        ],
        "bands": [
          "B04",
          "B08"
        ]
      }
    },
    "reduce_dimension_JADHX0569A": {
      "process_id": "reduce_dimension",
      "arguments": {
        "data": {
          "from_node": "load_collection_WJSXI6057X"
        },
        "reducer": {
          "process_graph": {
            "array_element_HROER8569Y": {
              "process_id": "array_element",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "index": 1,
                "return_nodata": true
              }
            },
            "array_element_VQKRJ1421M": {
              "process_id": "array_element",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                },
                "index": 0,
                "return_nodata": true
              }
            },
            "subtract_DRJET5871T": {
              "process_id": "subtract",
              "arguments": {
                "x": {
                  "from_node": "array_element_HROER8569Y"
                },
                "y": {
                  "from_node": "array_element_VQKRJ1421M"
                }
              }
            },
            "add_GADMZ0974A": {
              "process_id": "add",
              "arguments": {
                "x": {
                  "from_node": "array_element_HROER8569Y"
                },
                "y": {
                  "from_node": "array_element_VQKRJ1421M"
                }
              }
            },
            "divide_INLJN9314W": {
              "process_id": "divide",
              "arguments": {
                "x": {
                  "from_node": "subtract_DRJET5871T"
                },
                "y": {
                  "from_node": "add_GADMZ0974A"
                }
              },
              "result": true
            }
          }
        },
        "dimension": "bands",
        "context": null
      }
    },
    "save_result_CAOGW1055R": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "reduce_dimension_JADHX0569A"
        },
        "format": "NetCDF",
        "options": [
          "{}"
        ]
      },
      "result": true
    }
  },
  "parameters": [],
  "returns": {
    "schema": {
      "type": "boolean"
  }
}
}
```

**Comment by sophieherrmann** [comment]
Currently eodc only considers the number of input files (25 in this case) and the number of nodes in the process graph. This is definitely not the best solution, but the only really meaningful way to consider the extent would be to count pixels. (For collections with coarse resolution larger bounding box should be allowed.)  And we thought this is too compute intensive. 

Maybe another intermediate solution is to only consider the bounding box without the resolution of the used collection.

**Comment by sophieherrmann** [comment]
I now have a less strict "size checker" running on our dev back-end. Next to the number of input files and the number of nodes also an approximated version of the number of pixels is used. So for instance the provided process graph can now be executed as a sync job. 

@przell if you are interested please try it out

**Comment by przell** [comment]
Thanks for the fix! I currently don't have a task where I can fit this into as a test. But it will come up again for sure. Maybe interesting for @clausmichele.

**Comment by sophieherrmann** [comment]
The update is now also available in our prod environment.
