### ISSUE TITLE
All parameter schema's unecessarily have `"minItems": 0.0`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-openshift-driver#130]
While comparing the VITO and EODC process listings for https://github.com/openEOPlatform/documentation/issues/11 I noticed that all parameter/return schemas have a `"minItems": 0.0` field, e.g.

```json
    {
      "id": "absolute",
      "parameters": [
        {
          "name": "x",
          "schema": {
            "minItems": 0.0,
            "type": ["number", "null"]
          }
        }
      ],
      "returns": {
        "schema": {
          "minItems": 0.0,
          "type": ["number", "null"]
        }
      },
```

As far as I know jsonschema, minItems only makes sense for arrays (and it should be an integer, not float)

**Comment by m-mohr** [comment]
> As far as I know jsonschema, minItems only makes sense for arrays (and it should be an integer, not float)

Yes, indeed. 

I guess the default needs to be removed: https://github.com/Open-EO/openeo-eodc-driver/blob/822dbd3ccee25180cc48efd2f891504b6b5edc14/services/processes/processes/schema.py#L207

**Comment by sophieherrmann** [comment]
Yes we set a default as defined in the api. But I can remove it.

**Comment by m-mohr** [comment]
The default value in the API means that this is the value to be used if it is not provided (in the backend response), but you provide it explicitly, which is not the desired behavior. Would be good to remove it.

**Comment by sophieherrmann** [comment]
Makes sense, I already have a fix for this. I plan to bring it to dev today and then to prod as soon as possible.

**Comment by sophieherrmann** [comment]
Fix is deployed in production, checkout https://openeo.eodc.eu/v1.0/processes

**Comment by soxofaan** [comment]
Just curious: where did you fix this? There doesn't seem to be any recent updates on https://github.com/Open-EO/openeo-eodc-driver/branches

**Comment by sophieherrmann** [comment]
We moved our backend development to our private gitlab server.
