### ISSUE TITLE
Include properties for collections

### ISSUE THREAD

**Issue by jankovicgd** [Open-EO/openeo-openshift-driver#23]
Currently fetching a collection with `/collections/<collection_id>` yields an empty `properties` and `other_properties`. Extend the current implementation with new data

**Comment by lforesta** [comment]
#69 started this implementation

**Comment by jankovicgd** [comment]
`properties` and `other_properties` are merged into `summary`. Also `cube:dimension` replaces part of properties which is implemented with #86 

See more: https://github.com/Open-EO/openeo-api/issues/176
