### ISSUE TITLE
Update / endpoint to 0.4

### ISSUE THREAD

**Issue by jankovicgd** [Open-EO/openeo-openshift-driver#26]
`version` should be renamed to `api_version`
`backend_version` should be added
`title` should be added
`description` should be added

https://open-eo.github.io/openeo-api/apireference/#tag/Capabilities/paths/~1/get

**Comment by lforesta** [comment]
backend_version is tricky, because it must change for every change in the back-end. This could be based on the commit, but our back-end also depends on some key external packages, so not straightforward to track those changes too.

**Comment by jankovicgd** [comment]
Relevant: https://github.com/Open-EO/openeo-api/issues/195

**Comment by jankovicgd** [comment]
We should also think about moving the `/` endpoint to the capabilities service

**Comment by lforesta** [comment]
> We should also think about moving the `/` endpoint to the capabilities service

Yes, this has been implemented in recent updates. 

Also, the original comments were already incorporated time ago, closing.
