### ISSUE TITLE
Discovery endpoints should be available without login

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-openshift-driver#3]
Today I tried to include this backend in the openEO Hub, but the crawling process failed because all endpoints (except `/`) require login. I think that the discovery endpoints (`/collections`, `/processes`, `/output_formats`, `/service_types`) should be publicly available. Could you fix that so we can add this backend to the Hub? :)

**Comment by jankovicgd** [comment]
Solved with https://github.com/Open-EO/openeo-openshift-driver/pull/9. Will close the issue when it is pushed to production
